version: '2'
services:
    salon123-app:
        image: salon123
        external_links:
            - salon123-mysql:mysql
            - salon123-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/salon123?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    salon123-mysql:
        extends:
            file: mysql.yml
            service: salon123-mysql
    salon123-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: salon123-elasticsearch
